// vuejs-todo/src/components/todo-list/todo-entry/todoEntry.vue
<template>	
    <div class="todo-item">
        <!-- todo info -->
        <label>
            <input type="checkbox" v-model="todo.isDone" v-on:click="changeStatusOfTodo()" />
        </label>

        <span v-if="!editing" v-on:dblclick="toggleEdit()">{{ todo.text }}</span>
        <input v-if="editing" type="text" :ref="`${todo.id}`" v-model="newText" 
          v-on:keyup.enter="changeTextOfTodo()" 
          v-on:keyup.esc="toggleEdit()"/>

        <!-- actions -->
        <a class="action" v-on:click="deleteTodo(todo.id)"> x</a>                  
    </div>
</template>

<script>

// a single todo entry
export default {

  data: function() {
    return {
        editing: false,
        newText: this.todo.text
    }
  },

  props: ["todo"],

  name: "todoEntry",

  methods: {
    deleteTodo() {
      this.$store.dispatch("deleteTodo", this.todo.id)
    },

    changeStatusOfTodo() {
      this.$store.dispatch("changeStatusOfTodo", {
        newStatus: !this.todo.isDone,
        id: this.todo.id
      })
    },

    changeTextOfTodo() {
      this.$store.dispatch("changeTextOfTodo", {
        newText: this.newText,
        id: this.todo.id   
      }).then(() => {
        this.toggleEdit()
      })
    },
    toggleEdit() {
      this.editing = !this.editing
      if (this.editing) {
        this.$nextTick(() => this.$refs[this.todo.id].focus())
      }
    }
  }
}
</script>

// angular-todo/src/app/components/todo-list/todo-entry/todo-entry.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Todo } from "../../../model/todo.model";
import { Store } from '@ngxs/store';
import { TodoActions } from 'src/app/store/todo.actions';

@Component({
  selector: 'todo-entry',
  templateUrl: './todo-entry.component.html',
  styleUrls: ['./todo-entry.component.scss']
})
export class TodoEntryComponent {

  @Input("todo") todo: Todo;
  editing = false;
  newText = "";

  constructor(private store: Store) { }

  changeTextOfTodo(): void {
    this.store.dispatch(new TodoActions.ChangeText(this.todo.id, this.newText));
    this.toggleEdit();
  }

  changeStatusOfTodo(): void {
    this.store.dispatch(new TodoActions.ChangeStatus(this.todo.id, !this.todo.isDone));
  }

  deleteTodo(id: string): void {
    this.store.dispatch(new TodoActions.Delete(this.todo.id));
  }

  toggleEdit(): void {
    this.editing = !this.editing;
    if (this.editing) {
      this.newText = this.todo.text;
      setTimeout(() => document.getElementById(this.todo.id).focus(), 200);
    }
  }

}

<div class="todo-item" *ngIf="todo">
    <!-- todo info -->
    <label>
        <input type="checkbox" [ngModel]="todo.isDone" (click)="changeStatusOfTodo()" />
    </label>

    <span *ngIf="!editing" (dblclick)="toggleEdit()">{{todo.text}}</span>
    <input id="{{todo.id}}" *ngIf="editing" type="text" [(ngModel)]="newText" 
      (keydown.enter)="changeTextOfTodo()" 
      (keydown.esc)="toggleEdit()"/>

    <!-- actions -->
    <a class="action" (click)="deleteTodo(todo.id)"> x</a>                  
</div>
